<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQykmxgi\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQykmxgi/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQykmxgi.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQykmxgi\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQykmxgi\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Qykmxgi',
    'container.build_id' => '5de2bb99',
    'container.build_time' => 1516991600,
));
